# Generated by Django 5.1.15 on 2026-09-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_item', to='content.recipe'),
        ),
    ]
